import enum


class ErrorCodeEnum(str, enum.Enum):
    USER_ALREADY_EXISTS_FOR_LICENSE = "USER_ALREADY_EXISTS_FOR_LICENSE"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    CLUB_OWNER_ALREADY_EXISTS = "CLUB_OWNER_ALREADY_EXISTS"
    INVALID_TOKEN = "INVALID_TOKEN"
